merge my project into walnut
wechaty/puppet-walnut pull request #15
Opened 2021-11-29 10:59 UTC by fabian4

# What have achieved
- Message sending and receiving
- A simple ding-dong bot
- Organize the API document in markdown
- Put the puppet into the wechaty

2021-11-29 11:42 UTC, lijiarui requested changes
Please change as I request, and make GitHub action green, thanks!

2021-11-29 11:42 UTC, lijiarui commented on examples/ding-dong-bot.ts
> +import {log} from "wechaty-puppet";
I think we should import log from wechaty, instead of wechaty-puppet.

We should not use `wechaty-puppet` in the example code.

2021-11-29 11:42 UTC, lijiarui commented on local.ts
> +export const local = {
I think it would be better if you can add comments for this file and all of the arguments.

2021-11-29 11:42 UTC, lijiarui commented on src/config.ts
> +const config = {
I think it would be better if you can add comments for this file and all of the arguments.

2021-11-29 12:03 UTC, huan reviewed
We have to adapt the code base to the latest `wechaty-puppet@1.11` at first, please refer to

- #16

And make sure your PR can pass the CI with the latest main branch merged.

2021-11-29 12:31 UTC, fabian4 commented
### Here is the problem I have met when I run `npm test` on my local machine
~~~bash
> wechaty-puppet-walnut@0.1.41 lint:ts
> tsc --noEmit

node_modules/wechaty/dist/esm/src/wechaty-mixins/plugin-mixin.d.ts:91:15 - error TS1005: ',' expected.

91 export { type Plugable, type PluginMixin, type ProtectedPropertyPluginMixin, pluginMixin, };
                 ~~~~~~~~

node_modules/wechaty/dist/esm/src/wechaty-mixins/plugin-mixin.d.ts:91:30 - error TS1005: ',' expected.

91 export { type Plugable, type PluginMixin, type ProtectedPropertyPluginMixin, pluginMixin, };
                                ~~~~~~~~~~~

node_modules/wechaty/dist/esm/src/wechaty-mixins/plugin-mixin.d.ts:91:48 - error TS1005: ',' expected.

91 export { type Plugable, type PluginMixin, type ProtectedPropertyPluginMixin, pluginMixin, };
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 3 errors.
~~~

2021-11-29 12:35 UTC, huan commented
Make sure you are using TypeScript 4.5+

2021-12-01 12:47 UTC, huan requested changes
Please resolve the conflicts first before we can continue to review this PR.

Thank you very much.

2021-12-02 11:26 UTC, fabian4 commented
### There is another problem I have met when I run `npm run test`
~~~shell
src/puppet-walnut.spec.ts 2> TypeError: test.skip is not a function
src/puppet-walnut.spec.ts 2>     at file:///D:/juzi/puppet-walnut/src/puppet-walnut.spec.ts:19:6
src/puppet-walnut.spec.ts 2>     at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
src/puppet-walnut.spec.ts 2>     at async Promise.all (index 0)
src/puppet-walnut.spec.ts 2>     at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
src/puppet-walnut.spec.ts 2>     at async loadESM (node:internal/process/esm_loader:88:5)
src/puppet-walnut.spec.ts 2>     at async handleMainPromise (node:internal/modules/run_main:65:12)
~~~

### Details are as below
~~~shell
> wechaty-puppet-walnut@1.11.5 test
> npm run lint && npm run test:unit


> wechaty-puppet-walnut@1.11.5 lint
> npm-run-all lint:es lint:ts lint:md


> wechaty-puppet-walnut@1.11.5 lint:es
> eslint "src/**/*.ts" "tests/**/*.spec.ts" --ignore-pattern tests/fixtures/

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.5.2

Please only submit bug reports when using the officially supported version.

=============

> wechaty-puppet-walnut@1.11.5 lint:ts
> tsc --isolatedModules --noEmit


> wechaty-puppet-walnut@1.11.5 lint:md
> markdownlint README.md


> wechaty-puppet-walnut@1.11.5 test:unit
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" tap "src/**/*.spec.ts" "tests/**/*.spec.ts"

​ PASS ​ tests/integration.spec.ts 1 OK 841.445ms
​ PASS ​ src/version.spec.ts 1 OK 863.52ms
src/puppet-walnut.spec.ts 2> TypeError: test.skip is not a function
src/puppet-walnut.spec.ts 2>     at file:///D:/juzi/puppet-walnut/src/puppet-walnut.spec.ts:19:6
src/puppet-walnut.spec.ts 2>     at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
src/puppet-walnut.spec.ts 2>     at async Promise.all (index 0)
src/puppet-walnut.spec.ts 2>     at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
src/puppet-walnut.spec.ts 2>     at async loadESM (node:internal/process/esm_loader:88:5)
src/puppet-walnut.spec.ts 2>     at async handleMainPromise (node:internal/modules/run_main:65:12)
​ FAIL ​ src/puppet-walnut.spec.ts 2s
  command: D:\Application\ScoopApps\apps\nodejs\current\node.exe
  args:
    - src/puppet-walnut.spec.ts
  exitCode: 1
  signal: null

​ FAIL ​ TAP
 ✖ src/puppet-walnut.spec.ts

  test: TAP
  env: {}
  file: src/puppet-walnut.spec.ts
  timeout: 30000
  command: D:\Application\ScoopApps\apps\nodejs\current\node.exe
  args:
    - src/puppet-walnut.spec.ts
  stdio:
    - 0
    - pipe
    - 2
  cwd: D:\juzi\puppet-walnut
  exitCode: 1

​

                         
  � SUMMARY RESULTS �  
                         
​ FAIL ​ src/puppet-walnut.spec.ts 2s
  command: D:\Application\ScoopApps\apps\nodejs\current\node.exe
  args:
    - src/puppet-walnut.spec.ts
  exitCode: 1
  signal: null

​
Suites:   ​1 failed​, ​2 passed​, ​3 of 3 completed​
Asserts:  ​​​1 failed​, ​2 passed​, ​of 3​
​Time:​   ​2s​
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                  
----------|---------|----------|---------|---------|-------------------

Process finished with exit code 1

~~~

2021-12-02 12:02 UTC, huan commented
I'd like to suggest that you can refer to the latest version of codes in the main branch because everything is good (CI is green) with the main branch.

2021-12-02 14:50 UTC, fabian4 commented
Now I have fixed it and wait for approval @huan @lijiarui

2021-12-07 15:56 UTC, su-chang commented on local.ts
> +export const local = {
TODO: env is better than config file.

2021-12-07 15:57 UTC, su-chang commented on src/cache/cacheManager.ts
> +    os.homedir(), path.sep,
bizarre style

2021-12-07 15:58 UTC, su-chang commented on src/cache/cacheManager.ts
> +    this.baseDir = path.join(this.baseDir, path.sep, userId)
double `path.seq`

2021-12-07 15:59 UTC, su-chang commented on src/cache/cacheManager.ts
> +    // this.cacheContactRawPayload        = puppetCache.genContactClient()
Please remove useless code.

2021-12-07 16:00 UTC, su-chang commented on src/cache/cacheManager.ts
> +    // if (this.cacheContactRawPayload
ditto

2021-12-07 16:02 UTC, su-chang commented on src/help/message.ts
> +    messageId: stringRandom(20),
uuid is better

2021-12-07 16:03 UTC, su-chang commented on src/help/message.ts
> +    destinationAddress: [`tel:+86${to}`],
Please make sure all supported phone number is start with `tel:+86` or not.

2021-12-07 16:18 UTC, su-chang requested changes

2021-12-07 16:18 UTC, su-chang commented on src/help/message.ts
> +  void post(api.sendMessage, {
It's better to replace `api` by `API`. And maybe we should add a method to generate parameters.

2021-12-07 16:18 UTC, su-chang commented on src/help/message.ts
> +  // post(api.sendMessage, {
Please remove useless code.

2021-12-07 16:18 UTC, su-chang commented on src/help/request.ts
> +  setTimeout(updateToken, 2 * 60 * 60 * 60 * 60)
bug

2021-12-07 16:18 UTC, su-chang commented on src/help/request.ts
> +export function get (params: {}, url: string) {
`params: {}` -> `params = {}` ?

2021-12-07 16:18 UTC, su-chang commented on src/help/struct.ts
> +    messageItem: string,
Please add comments and example for these attributes.

2021-12-07 16:18 UTC, su-chang commented on src/sever/logging.ts
> +    console.error(thrownError)
Why use `console.error` here?

2021-12-07 16:18 UTC, su-chang commented on src/sever/logging.ts
> +  } catch (e: any) {
Please do not use `any` type for exact type.

2021-12-07 16:18 UTC, su-chang commented on src/sever/routers.ts
> +router.post('/sms/messageNotification/sip:20210401@botplatform.rcs.chinaunicom.cn/messages', async (ctx: any) => {
Please add method for this router.

2021-12-07 16:18 UTC, su-chang commented on src/sever/routers.ts
> +router.post('/sms/deliveryNotification/sip:20210401@botplatform.rcs.chinaunicom.cn/status', async (ctx: any) => {
ditto

2021-12-07 16:18 UTC, su-chang commented on tests/fixtures/smoke-testing.ts
> +  VERSION
Please make all code style consistent.

2021-12-08 15:52 UTC, su-chang commented on src/cache/cacheManager.ts
> +    this.baseDir = path.join(this.baseDir, path.sep, PuppetWalnut.sipId, path.sep)
```
this.baseDir, path.sep
```

`this.baseDir` already contains `path.seq`

2021-12-08 15:53 UTC, su-chang commented on src/cache/cacheManager.ts
> +      this.cacheMessageRawPayload    = undefined
code style

2021-12-13 06:05 UTC, fabian4 commented
@huan ping

2021-12-13 06:15 UTC, huan approved these changes
LGTM

However, I have some enhancing suggestions for this repo, they should be fixed before or after this PR has been merged:

1. keep the `.eslintrc.cjs` clean. Only add `disable` rules in a specific file so that we can always follow the best practice rules from `@chatie/eslint-config` for our Wechaty community repos.
2. use the `.webp` image. This is an enforced rule for our website and should be followed in our code repos.
3. use English for file name instead of Chinese, for better URL encoding friendly
4. keep all file names be **lowercased**
5. remove `wechaty` dependency in the Puppet repo, or it will cause future problems. 

At last, thank you very much for improving the walnut puppet, I hope it can be publish to Beta to our community soon!

2021-12-13 06:17 UTC, lijiarui requested changes
Hi @febian

I think we should change as @huan  requested, then merge this PR.

2021-12-13 07:18 UTC, fabian4 commented
However，the `wechaty` dependency is needed in my example project `ding-dong-bot`. Removing it may fail the test.
So can we put it in the `devDependencies` instead ? @huan

2021-12-13 07:20 UTC, huan commented
No. The example bot should dependent on `wechaty` too.

You can learn from our puppet template mock at https://github.com/wechaty/puppet-mock/blob/main/examples/ding-dong-bot.ts

2021-12-13 07:46 UTC, fabian4 commented
Now I have done the work as requested and I hope everything is fine by now

2021-12-13 07:57 UTC, lijiarui commented
Please get @su-chang approval first, then I will review this PR.

2021-12-13 10:29 UTC, su-chang commented on src/puppet-walnut.ts
> +      timestamp: Date.parse(new Date().toString()),
It's better to use `Date.now()` to replace `Date.parse(new Date().toString())`.

2021-12-13 10:43 UTC, su-chang requested changes

2021-12-13 10:43 UTC, su-chang commented on src/help/request.ts
> +  authorization: 'accessToken ',
Unexpected space here.

2021-12-13 10:43 UTC, su-chang commented on src/help/request.ts
>      data: {
Why do not set `params` to `data`?

2021-12-13 10:43 UTC, su-chang commented on src/puppet-walnut.ts
> +      id: '',
Do not set id with empty string.

2021-12-13 10:43 UTC, su-chang commented on src/puppet-walnut.ts
> +      avatar: 'https://raw.githubusercontent.com/fabian4/puppet-walnut/dev/docs/images/avatar.jpg',
Put this default avatar url to config file.

2021-12-13 14:53 UTC, su-chang commented on src/help/request.ts
> +      ...data,
```ts
{
  data: {
    ...params,
  },
}
```

is same to:

```ts
{
  data,
}
```

2021-12-14 02:07 UTC, su-chang requested changes

2021-12-14 02:07 UTC, su-chang commented on examples/ding-dong-bot.ts
> +const puppet = new PuppetWalnut({})
I think it's no need to pass an empty object.

2021-12-14 02:07 UTC, su-chang commented on src/puppet-walnut.spec.ts
> +  const puppet = new PuppetWalnut({})
ditto

2021-12-14 02:23 UTC, su-chang approved these changes
LGTM

2021-12-14 02:38 UTC, fabian4 commented
@lijiarui ping

2021-12-18 08:05 UTC, lijiarui approved these changes
Good job！

2021-12-18 08:10 UTC, merged