feat: implement contact function
wechaty/puppet-walnut pull request #19
Opened 2022-01-11 03:18 UTC by fabian4

2022-01-11 03:54 UTC, su-chang requested changes

2022-01-11 03:54 UTC, su-chang commented on src/cache/cacheManager.ts
> +      if (key !== selfId) {
Why skip `selfId`?

BTW, it's better to rename `key` as `contactId`.

2022-01-11 03:54 UTC, su-chang commented on src/cache/cacheManager.ts
> +      if (!CacheManager.reg.exec(contactId)) {
I think this regular check should not be processed here.

2022-01-11 03:54 UTC, su-chang commented on src/cache/cacheManager.ts
> +    await this.cacheContactRawPayload.set(PuppetWalnut.chatbotId, { name: PuppetWalnut.chatbotId, phone: PuppetWalnut.chatbotId })
code style

2022-01-11 03:54 UTC, su-chang commented on src/puppet-walnut.ts
> +      PuppetWalnut.cacheManager?.setContactAlias(contactId, alias)
Maybe need try catch here.

It's better abstract a method, and use it anywhere.
```ts
function getCacheManager () {
  if (!cacheManager) {
    throw new Error()
  }
  return cacheManager
}
```

2022-01-11 03:54 UTC, su-chang commented on src/puppet-walnut.ts
> +    return FileBox.fromUrl(config.avatarUrl)
If 5G not support contact avatar, it's better always return a default `FileBox`, no need return void.

2022-01-11 03:54 UTC, su-chang commented on src/puppet-walnut.ts
> +    send(conversationId, message!.messageList[0]!.contentText)
It's dangerous to use `!` and `[0]` here.

2022-01-11 03:54 UTC, su-chang commented on src/sever/parse.ts
> +  void PuppetWalnut.cacheManager?.setContact(
code style

2022-01-11 03:54 UTC, su-chang commented on src/sever/sever.ts
> +import { log } from 'wechaty-puppet'
Maybe we should import `log` from `wechaty-puppet` only in one file, e.g. 
1. import `log` from `wechaty-puppet` in `config.ts`
2. export `log` in `config.ts`
3. use log module from `config.ts`

2022-01-11 06:48 UTC, su-chang requested changes

2022-01-11 06:48 UTC, su-chang commented on src/config.ts
> +export { log }
It's better merge `config` and `log` into one export object.

2022-01-11 07:24 UTC, su-chang commented on src/cache/cacheManager.ts
> +  static reg: RegExp = /^1(3\d|4[5-9]|5[0-35-9]|6[567]|7[0-8]|8\d|9[0-35-9])\d{8}$/
This reg is not related to `CacheManager` class now, please move it to `util` file.

2022-01-11 07:25 UTC, su-chang commented on src/config.ts
> +export { config, log }
code style

```ts
export {
  config,
  log,
}
```

2022-01-11 07:33 UTC, su-chang approved these changes
LGTM

2022-01-12 04:22 UTC, lijiarui requested changes

2022-01-12 04:22 UTC, lijiarui commented on examples/ding-dong-bot.ts
> +import { log } from '../src/config.js'
We should import log from `wechaty-puppet`, instead of `../src/config.js`

Since we should show the best practice in the example code and for newbies they don't have config.js file.

2022-01-12 06:48 UTC, lijiarui approved these changes
Good job

2022-01-12 06:48 UTC, lijiarui commented
This PR will be merged after all CI turn green.

2022-01-13 04:02 UTC, merged