Feat: support post message
wechaty/puppet-walnut pull request #27
Opened 2022-04-11 13:32 UTC by fabian4

https://github.com/wechaty/wechaty/issues/2245

2022-04-12 02:53 UTC, huan commented
Which issue does this PR related to?

Please always link them together.

2022-04-12 12:37 UTC, fabian4 commented
ping @huan @su-chang

2022-04-12 12:39 UTC, huan commented on src/help/message.ts
> +import type { SayablePayload } from 'wechaty-puppet/dist/cjs/src/schemas/sayable'
Never use deep import.

Use `PUPPET.payloads.Sayable` instead.

2022-04-12 12:39 UTC, huan commented on src/help/message.ts
> +export async function sendPostMessage (to: string, postPayload: PUPPET.payloads.Post) {
Rename `to` to `contactId` to make the param name more clear.

2022-04-12 12:45 UTC, huan commented on src/help/message.ts
> +  const img = postPayload.sayableList[2] as SayablePayload
If you need a `title + description + image` combo, then it seems that you can use a UrlLink Payload.

Your payload can be

```ts
PUPPET.payloads.sayable.url({
  url: 'https://google.com',
  title: 'Google',
  description: 'description',
  thumbnailUrl: 'https://xxx.com/img.jpg',
})
```

The only problem is that the `url` and `title` in the payload are required, which means you need to set those two values. (a '' might be a workaround, however, more suggestions are welcome.)

2022-04-12 12:46 UTC, su-chang commented on src/help/message.ts
> +  sendMessage(to, {
The params is complicated indeed, it's better to add a new function to generate it.

BTW, test case will make the function more reliable.

2022-04-12 12:49 UTC, su-chang commented on src/help/message.ts
> +    throw new Error('Wrong Post!!!')
Error message without detail info, a little help for debugging only.

2022-04-12 12:50 UTC, su-chang commented on src/puppet-walnut.ts
> +        if (files[0]!.contentType === 'text/vcard') {
Please think more about using `!`.

2022-04-12 12:54 UTC, su-chang commented on src/help/message.ts
> +  const title = postPayload.sayableList[0] as SayablePayload
It seems that the attrs of `postPayload.sayableList` must in order?

2022-04-12 12:59 UTC, su-chang requested changes
BTW, all commits with the same commit message is not a good habit.

2022-04-14 12:04 UTC, su-chang approved these changes
LGTM

2022-04-14 12:35 UTC, huan commented on src/help/message.ts
> +  sendMessage(contactId, {
Does this nested function necessary?

Embed the exact code to reduce the complexity if possible.

2022-04-14 12:38 UTC, huan approved these changes
I have no more suggestions.

Looking forward to seeing the Post support for walnut online soon.

Thank you very much for the implementations!

2022-04-14 12:38 UTC, huan commented on src/help/message.ts
> +  sendMessage(contactId, {
Does this nested function necessary?

Embed the exact code to reduce the complexity if possible.

2022-04-14 13:22 UTC, merged